### ISSUE TITLE
touch commands are not supported

### ISSUE THREAD

**Issue by ndimer** [piotrekkmt/chromedriver-appium#1]
Hi,

It seems that this version of webdriver doesn't support touch-related commands. It returns perform touch not implemented error.  

Would it be possible to recompile the driver to support the latest chromedriver changes?

Thanks.

**Comment by idxn** [comment]
which touch action did you use? I try the tap action and it's fine for me.

**Comment by piotrekkmt** [comment]
Since tap actions are supported, closing the issue. Thanks for helping out @idxn.
